### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by luisfgfurtado** [jamesandres/ColumnCopy#14]
I have tested in OSX Chrome and just doesn't work.

**Comment by jamesandres** [comment]
Hi @luisfgfurtado, I built this extension on OSX. All I have is a MacBook Pro :).

Have you tried restarting chrome after enabling the extension? Are you running any other extensions (they might conflict)? What version of Chrome?

What behaviour are you experiencing?

**Comment by luisfgfurtado** [comment]
Hi @jamesandres, actually I reinstall the extension and it's working perfectly now.
I don't know why didn't work before.
Thank you, this extension will be very useful to me. :+1:
